name: 'devstack-action'
description: 'Deploy OpenStack with devstack'
inputs:
  branch:
    description: 'Name of the branch to deploy'
    default: 'master'
  conf_overrides:
    description: 'Configuration overrides for devstack'
    default: ''
  enabled_services:
    description: 'Add or remove services to deploy via devstack'
    default: ''
  log_dir:
    description: 'Directory for logs'
    default: '/tmp/devstack-logs'
runs:
  using: "composite"
  steps:
    - name: Install python pip
      run: python -m pip install --upgrade pip
      shell: bash
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#mysql
    - name: Start MySQL
      run: sudo systemctl start mysql.service
      shell: bash
    # See http://lists.openstack.org/pipermail/openstack-discuss/2020-October/018060.html
    - name: Remove python3-simplejson
      run: sudo apt-get purge -y python3-simplejson
      continue-on-error: true
      shell: bash
    - name: Checkout Devstack
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}
        repository: openstack/devstack
        path: ./devstack
    - name: Configure devstack
      run: |
        cat <<EOF > local.conf
        [[local|localrc]]
        ADMIN_PASSWORD=secret
        DATABASE_PASSWORD=root
        RABBIT_PASSWORD=secret
        SERVICE_PASSWORD=secret
        SWIFT_HASH=1234123412341234
        LOGFILE=${{ inputs.log_dir }}/devstack.log
        EOF
        # horizon does not work in github action, permission error
        # dstat log takes too much memory to be stored by log artifacts
        ENABLED_SERVICES=",-horizon,-dstat"
        if [[ "${{ inputs.enabled_services }}" != "" ]]; then
          ENABLED_SERVICES+=",${{ inputs.enabled_services }}"
        fi
        echo "ENABLED_SERVICES+=${ENABLED_SERVICES}" >> local.conf
        if [[ "${{ inputs.conf_overrides }}" != "" ]]; then
          echo "${{ inputs.conf_overrides }}" >> local.conf
        fi
      working-directory: ./devstack
      shell: bash
    - name: Run devstack
      run: ./stack.sh
      working-directory: ./devstack
      shell: bash
