name: 'devstack-action'
description: 'Deploy OpenStack with devstack'
inputs:
  branch:
    description: 'Name of the branch to deploy'
    default: 'master'
  conf_overrides:
    description: 'Configuration overrides for devstack'
    default: ''
  enabled_services:
    description: 'Add or remove services to deploy via devstack'
    default: ''
  log_dir:
    description: 'Directory for logs'
    default: '/tmp/devstack-logs'
  enable_workaround_docker_io:
    description: 'Enable or disable workaround for docker.io'
    default: 'true'
  force:
    description: 'Allow running devstack on unsupported distro'
    default: 'no'
runs:
  using: "composite"
  steps:
    - name: Install python pip
      run: python -m pip install --upgrade pip
      shell: bash
    - name: Erase MySQL package
      run: sudo apt-get purge mysql-* || true
      shell: bash
    # This is to avoid RabbitMQ to fail at startup because a wrong version of erlang was installed
    - name: Workaround for RabbitMQ
      run: |
        sudo apt-get purge -y esl-erlang || true
        sudo apt-get install -y erlang rabbitmq-server || true
      shell: bash
    - name: Workaround for docker.io
      if: ${{ inputs.enable_workaround_docker_io == 'true' }}
      run: |
        sudo apt-get install -y runc || true
      shell: bash
    - name: Remove unwanted packages
      run: sudo apt-get purge -y python3-simplejson python3-pyasn1-modules postgresql* || true
      shell: bash
    - name: Checkout Devstack
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
        repository: openstack/devstack
        path: ./devstack
    - name: Configure devstack
      run: |
        cat <<EOF > local.conf
        [[local|localrc]]
        ADMIN_PASSWORD=secret
        DATABASE_PASSWORD=root
        RABBIT_PASSWORD=secret
        SERVICE_PASSWORD=secret
        SWIFT_HASH=1234123412341234
        LOGFILE=${{ inputs.log_dir }}/devstack.log
        USE_PYTHON3=True
        INSTALL_TEMPEST=False
        GIT_BASE=https://github.com
        EOF

        # Overriding target release for unmaintained versions
        # otherwide devstack will fail to clone some repos.
        TARGET_BRANCH=${{ inputs.branch }}
        if [[ "${{ inputs.branch }}" == *"yoga"* ]]; then
            TARGET_BRANCH="yoga-eom"
        fi
        echo "TARGET_BRANCH=${TARGET_BRANCH}" >> local.conf

        # horizon does not work in github action, permission error
        # dstat log takes too much memory to be stored by log artifacts
        # tempest must be disabled otherwise it will get installed still
        ENABLED_SERVICES=",-horizon,-dstat,-tempest"
        if [[ "${{ inputs.enabled_services }}" != "" ]]; then
          ENABLED_SERVICES+=",${{ inputs.enabled_services }}"
        fi
        echo "ENABLED_SERVICES+=${ENABLED_SERVICES}" >> local.conf

        # This must stay at the end to allow any overrides
        cat << EOF_CONF_OVERRIDES >> local.conf
        ${{ inputs.conf_overrides }}
        EOF_CONF_OVERRIDES
      working-directory: ./devstack
      shell: bash
    - name: Run devstack
      env:
        FORCE: ${{ inputs.force }}
      run: ./stack.sh
      working-directory: ./devstack
      shell: bash
